config/routes.rb
Rails.application.routes.draw do
  resources :swiits do
    collection do
      post :confirm
    end
  end
  root 'swiits#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/swiit.rb
class Swiit < ApplicationRecord
  validates :title, presence: true
  validates :content, length: {minimum: 1}, length: {maximum: 140}, presence: { message: " is too long (Max. 140 characters) or is not writen yet." }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/swiits_controller.rb
class SwiitsController < ApplicationController
    before_action :set_swiit, only: [:show, :edit, :update, :destroy]
    def new
      @swiit = Swiit.new
    end
  
    def index
      @swiits = Swiit.all
    end
  
  
    def create
      @swiit = Swiit.new(swiit_params)
      if params[:back]
        render :new
      else
        if @swiit.save
          redirect_to swiits_path, notice: "New Swiit have been created!"
        else  
        render :new
        end
      end
    end
    
    def confirm
      @swiit = Swiit.new(swiit_params)
      render :new if @swiit.invalid?
    end
  
    def update
      if @swiit.update(swiit_params)
        redirect_to swiits_path, notice: "have been edited the Swiit N.#{@swiit.id} from title: #{ @swiit.title }!"
      else
        render :edit
      end
    end
  
    def edit
    end

    def show
    end
  
    def destroy
      @swiit.destroy
      redirect_to swiits_path, notice:"have been deleted the swiit from title: #{@swiit.id}.-#{ @swiit.title }!"
    end
  
    private
    def swiit_params
      params.require(:swiit).permit(:title, :content)
    end
  
    def set_swiit
      @swiit = Swiit.find(params[:id])
    end
  end
  

app/controllers/swiits_controller_test.rb
class SwiitsController < ApplicationController
  before_action :set_swiit, only: [:show, :edit, :update, :destroy]
  def index
    @swiits = Swiit.all
  end

  def new
    @swiit = Swiit.new
  end

  def create
    @swiit = Swiit.new(swiit_params)
    if params[:back]
      render :new
    else
      if @swiit.save
        redirect_to swiits_path, notice: "New Swiit have been created!"
      else  
      render :new
      end
    end
  end

  def confirm
    @swiit = Swiit.new(swiit_params)
    render :new if @swiit.invalid?
  end
  
  def edit
  end


  def update
    if @swiit.update(swiit_params)
      redirect_to swiits_path, notice: "have been edited the Swiit N.#{@swiit.id} from title: #{ @swiit.title }!"
    else
      render :edit
    end
  end

  
  def show
  end

  def destroy
    @swiit.destroy
    redirect_to swiits_path, notice: "have been deleted the swiit from title: #{@swiit.id}.-#{ @swiit.title }!"
  end

  private
  def swiit_params
    params.require(:swiit).permit(:title, :content)
  end

  def set_swiit
    @swiit = Swiit.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/swiits_helper.rb
module SwiitsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_swiits_path
    elsif action_name == 'edit'
      swiit_path
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Swiit</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="container">
      <div class="navbar" id="main-navbar">
        <h1>Swiit</h1>
      </div>
      <%= yield %>    
    </div>
  </body>
  <footer>
    <h1>Keep sharing Swiits!</h1>
  </footer>
</html>

app/views/swiits/_form.html.erb
<div class="mainbody">
  <p><%= notice %></p><br>
  <div class="col1">
    <p class="swiit-title">N. Swiits :<%= @swiit.id %></p>
  </div>
  <div class="col2">
    <%= form_with(model: @swiit, local: true, url: choose_new_or_edit ) do |form| %>
      <% if @swiit.errors.any? %>
      <div id="error_explanation">
        <h2><%= @swiit.errors.count %> errors founded</h2>
        <ul>
        <% @swiit.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
      <% end %>
      <div class="swiit_title">
        <%= form.label :title %>
        <%= form.text_field :title %> 
      </div>
      <div class="swiit_content">
        <%= form.label :content %>
        <%= form.text_area :content, size: "40x10" %>
      </div>
      <%= form.submit 'Post' %>
    <% end %>
  </div>
  <div class="col3">
    <table>
      <tr>
        <td><%= link_to "Swiit home", swiits_path, class: "btn-new"%></td>
      <tr>     
    </table>
  </div>    
</div>

app/views/swiits/confirm.html.erb
<div class="container">
  <div class="navbar" id="main-navbar">
    <h1>Swiiter</h1>
  </div>
  <div class="mainbody">
    <p><%= notice %></p><br>
    <div class="col1">
    </div>
    <div class="col2">
      <h3>Send with the following contents</h3>
      <%= form_with(model: @swiit, url: swiits_path, local: true) do |form| %>
        <%= form.hidden_field :title %>
        <%= form.hidden_field :content %>
        <p>title:<%= @swiit.title %></p>
        <p>Content:<%= @swiit.content %></p>
        <%= form.submit  "post" %>
        <%= form.submit "back", name: 'back' %>
      <% end %>
    </div>
    <div class="col3">
      <table>
        <tr>
          <td><%= link_to "Swiit home", swiits_path, class: "btn-new"%> </td>
        <tr>     
      </table>
    </div>    
  </div>
</div>

app/views/swiits/edit.html.erb
<%= render 'form'%>

app/views/swiits/index.html.erb
<div class="mainbody">
  <p><%= notice %></p><br>
  <div class="col1">     
  </div>
  <div class="col2">
    <table class="main-swiits">
    <% @swiits.each do |swiit| %>
    <tr class="tr-displays">
      <td class="swiit-content", colspan="3"><%= swiit.content%> </td>
      <td></td>
      <td></td>
    </tr>
    <tr class="tr-links">
      <td><%= link_to 'Details', swiit_path(swiit.id), class: "btn-D"%></td>
      <td><%= link_to 'Edit', edit_swiit_path(swiit.id), data: { confirm: 'Can I really edit it?' }, class: "btn-D"%></td>
      <td><%= button_to 'Delete', swiit_path(swiit.id), method: :delete, data: { confirm: 'Are you sure to delete it?' }, class: "btn-D"%></td>
    </tr>
    <% end %>
    </table>
  </div>
  <div class="col3">
    <table>
      <tr>
        <td><%= link_to 'Post new Swiit ', new_swiit_path, class: "btn-new" %> </td>
      <tr>     
    </table>
  </div> 
</div>

app/views/swiits/new.html.erb
<%= render 'form'%>
  
 

app/views/swiits/show.html.erb
<div class="col1">     
</div>
<div class="show">
  <h1>Swiit details screen</h1><br>
  <p>Title:<br><br><%= @swiit.title %></p><br> 
  <p> Content:<br><br><%= @swiit.content %></p>  
</div>
<div class="col3">
  <table>
    <tr>
      <td><%= link_to "swiit home", swiits_path, class: "btn-new" %> </td>
    <tr>     
  </table>
</div> 